version: 2.1

jobs:
  build:
    docker:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./public && npm install && npm run build && npm install react-scripts@5.0.1 
      - run: npm audit fix --force
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd ./public && npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
        image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: 
          name: deploy
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync build s3://challenge-fsl-test --delete --exact-timestamps;
            fi
    

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test