version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint dependencies
          command: npm run lint
      - run:
          name: Prettier dependencies
          command: npm run prettier
      - run:
          name: Test
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync build s3://challenge-fsl-test --delete --exact-timestamps;
            fi
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main